site:
  title: Teebeutel Documentation
  url: https://teebeutel.entropia.de
  start_page: intro::index.adoc

content:
  sources:
  - url: ../Teebeutel-Hardware
    branches: 
      - HEAD
    start_path: docs
  - url: ../Teebeutel-Expansion
    branches:
      - HEAD
    start_path: docs
  - url: ../Teebeutel-Documentation
    branches:
      - HEAD
    start_path: docs
ui:
  bundle:
    url: ui/build/ui-bundle.zip
    snapshot: true
asciidoc:
    attributes:
        icons: font
