name: Build and Deploy docs
on:
  push:
    paths:
      - 'docs/**'
      - 'ui/**'
      - 'antora-playbook.yml'
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: 16

      - name: Install ui dependencies
        run: npm install
        working-directory: ui

      - name: Build ui
        run: npx gulp build
        working-directory: ui

      - name: Pack ui
        run: npx gulp bundle:pack
        working-directory: ui

      - name: Install antora
        run: npm install

      - name: Build docs
        run: npx antora antora-playbook.yml --fetch
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: docs-build
          path: build/site/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docs-build
          path: build
      - name: Import SSH-Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSHKEY }}" >> ~/.ssh/id_dsa
          chmod 600 ~/.ssh/id_dsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - name: Deploy
        run: |
          rsync -raz --delete --no-motd --no-o --no-g build/ deploy@teebeutel.entropia.de:/var/www/teebeutel.entropia.de/html/
