name: Build and Deploy docs
on:
  repository_dispatch:
    types: [update_docs]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Antora
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: antora-playbook.yml
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: docs-build
          path: build/site/
